//
//  myData.swift
//  Data Testing Example
//
//  Created by The Delta School Student on 2/5/20.
//  Copyright © 2020 The Delta School Student. All rights reserved.
//

import Foundation

let characterNameArray = ["Anna WeatherBee", "Benjamin Topaz", "Helen Borden", "Katniss Grange", "Merida Evernever", "Lili Felton", "Toni Blossom", "Camila Weatherbee",  "Tori Blossom", "Fred Borden", "Elsa Parkinson"]
// ^^ That has 5 characters, remember numbering starts at 0, not 1
// Anna = 0, Ben = 1, Helen = 2, etc
let descriptionArray = ["You are the daughter of Camila Weatherbee and the fiance of Benjamin Topaz. You work as a grade school math teacher who loves to dance (you are a flapper after all) and hate it when people chew with their mouths open. ", "You are an orphan adopted by Dan Spellman and the fiance of Ana Weatherbee. You are currently in college working on your Masters and you love to hit the town after a long night.", "You are a flapper who is desperately in love with Benjamin Topaz. However, you must not let this be known because you are also... the murderer. You hate Ana with a passion for taking your lover and will let this be known in the most gruesome ways.", "You are the detective. Eventually there will be a murder and it will be up to you to solve it. You are undercover as a flirtatious superflapper. You are also one of the Weatherbee family friends.", "You are Luke's sister and one of Benjiman's friends. You are pursuing your passion of carpenting and tend to tell people off for their immaturity because you can't stand immature people! You also really don't like it when people are arguing because it makes you feel insecure. ", "You are one of Ana's friends from high school. You work as a data analyst and always make sure to say what you think - blunt honesty is the best policy. You also tend to speak for your younger sister Penelope who is generally too shy to do so for herself.", "You are one of Anna's high school friends. You are an overly serious architect who has come to believe that your ideas are the most important and your opinions are always correct. You've always despised Tori, your twin sister, who is wasting her life being a halfwitted flapper instead of marrying life a good girl.", "You are the mother of Ana Weatherbee. You are an English teacher at a highschool. You greatly disapprove of flappers and that sort of nonsense and are very glad your daughter is finally settling down and marrying.", "You are the twin sister of Toni. You are a superflapper whose one goal in life is to enjoy yourself. You're still young and want to live like it. You don't know how your twin Toni can live within the structured walls he has built for himself. You yourself like to go with the flow of things and make no plans.", "You are the brother of Helen Borden. You are consitently trying to keep your little sister in check because she never seems to know when to stop. If she does not get what she wants... well, then again, she usually gets what she wants.", "You are the aunt of Benjamin Topaz, your favorite nephew. Your favorite hobbies consist of dancing and baking, occasionally at the same time."]

let notificationTimeHOUR = [6, 7, 8]
let notificationTimeMIN = [00, 10, 25, 30, 35, 45, 55, 05, 10, 15, 25, 35, 40, 45, 50, 55, 05, 10, 15, 20, 28, 35]
//Benjamin Topaz
let notificationContent0 = ["Wanting to ensure you look your best, you ask the waitress Dorothy where the bathroom is so you can look in a mirror."]
//Helen Borden
let notificationContent1 = ["You notice your true love, Benjamin, leaving the room and leave to follow with murder on your mind. When you find him, you will profess the love you have always felt for him before you kill him with your cap gun for never recognizing how you were made for him.", "Satisfied with how your plan is going, you pretend to mourn and comfort Anna in her grief. However, you are laughing on the inside. The silly girl will never realize you are the murderer.  If only your sweet Benjamin had never fallen for her and her tricks. None of this would have happened if she had not captured him. She was the murderer, not yourself.", "You notice your brother has been watching you suspiciously and decide to figure out what it is about. You tell Anna you are going to get her some tissues and leave towards the bathroom. As you thought he would, Fred follows you. you decide that if he has found out you are the murderer then you will have to take him out." ,"You begin to get nervous. What if someone figures out that you are the murderer? You look down at your hands frequently. Did you get all the blood off? You attempted to rub it all off, but it stuck more than you thought it would.", "You invite Merida Evernever out to the kitchen to talk about her suspicions about who the murderer is. As soon as you get there... you will kill her. She does not understand and she does not need to. Someone should teacher her that she should not blackmail people when she does not understand the truly emotional things going on around her." , "How dare they? How dare they think, Toni, TONI killed Benjamin and Fred and Merida? He couldn't even kill a mosquito! The one bug that every single human has killed? He would let it sit on his arm and suck all the blood out of his body! Just thinking about how terribly gullible everyone is makes your blood boil. You decide to kill Camila so she can finally know who the true creator of chaos and murder. Plus, this would be the fourth sword to pierce Anna's heart. The fourth person she cared about that has ended up dying. You've always liked the number four." , "You notice Toni leaving and decide to follow him. You still cannot wrap your mind around how everyone was so willing to believe that he was the murderer when he most definitely was not. The poor guy needs to be put out of his misery."]
//Katniss Grange
let notificationContent2 = ["You examine the body of Benjamin Topaz and see lipstick on his collar.", "You notice Toni's care for Anna and also how others seem to believe he is the murderer. However, you are not quite convinced yet. Although he could have murdererd Benjamin out of pure envy and hate, he does not seem to be the type of person to do so." , "You go to observe the body and realize that it must have been pushed down the stairs in an attempt to be hidden. However, the body is covered in blood. This means the murderer must also have blood on his/her hands." , "You notice how Helen has been following people in and out of the dining hall and decide to follow her. What if this 'innocent and fragile' girl is actually the murderer? If you see her pull a weapon, you will take it from her before she can harm more people." , "You now have Helen's gun and bring her out to meet the others. You then force her to confess what she has done and who she has murdererd before you leave to put her in prison."]
//Camila Weatherbee
let notificationContent3 = ["Although you are afraid that a murderer is loose at your daughter's engagement party, you voice your opinion that perhaps this is not as bad as it seems. After all, you always disapproved of Benjamin who you thought was a bad influence on your daughter." , "You begin to be truly worried about the safety of yourself and your daughter. What if someone tries to kill one of the two of you next? You begin to closely watch the people around you. Who would be able to kill someone so ruthlessly? Who is that uncompassionate? Could it be Toni? You share your thoughts with everyone.", "You loudly confront Toni abot whether or not he murdered Benjamin Topaz. Everyone should know that he is the murderer." , "You decide to go look at the dead bodies again and ask Helen to accompany you. She has always been such a nice girl. You know that if something were to go wrong, she would be there for you."]
//Toni Blossom
let notificationContent4 = ["You have been in love with Anna since high school and do not waste any time going to comfort her. Although it is sad that her fiance died, perhaps it is for the best. Maybe you have a chance with her now..." , "You begin to ralize that people think you are the murderer. You would never do such a thing! Why do people think something like this? You only want everyone to be happy! You begin to share your thoughts with everyone around you.","Unable to bear everyone's accusations any longer, you leave to collect yourself."]
//Elsa Parkinson
let notificationContent5 = ["You notice that Toni is making moves on the girl who was almost your niece and are exteremely angry about it. You tell everyone that you believe he murdered your favorite nephew so he could get his hands on her."]
//Anna Weatherbee
let notificationContent6 = ["You are terribly distraught. What shall you do now that your beloved is dead? What is left in life for you? Thank God for Toni. He has always been a good friend with a shoulder always ready for you to cry on."]
//Lili Felton
let notificationContent7 = ["You are disgusted by Toni who is making moves on your best frined Anna and start telling people that he must be the one who killed Benjamin since he'd always loved Anna."]
//Fred Borden
let notificationContent8 = ["You suspect that your sister, Helen, is the murderer. After all, she has always been 'in love' (or dangerously obsessed over) Benjamin Topaz. You remember the day that Ben, one of your friends, proposed to Anna and she accepted. You were there. However, you also remember how Helen reacted when she found out - throwing glass bottles and hysterically sobbing. You would not put it past her to have premeditated this murder and decide to confront her about it. Lucky for you, she has just gotten up to go to the bathroom."]
//Merida Evernever
let notificationContent9 = ["You begin to suspect that Helen Borden is the murderer. After all, she was always jealous of Anna. You decide to tell her of your beliefs and tell her that if she does not stop then you will tell everyone and make sure that the rest of Helen's life is living hell. After all, someone has to control her."]
//Tori Blossom
let notificationContent10 = ["You have never gotten along with your brother. He has always seemed to look down on you and expected you to be perfect when all you wanted to be was yourself. However, he is no murderer and you decide to tell people such. You decide that Helen Borden must be the murderer. After all, if anyone wanted to make Anna this terribly upset it would be her. You immediately begin telling people of your thoughts."]
//Everyone
let notificationContentEveryone0 = ["Welcome to Anna Weatherbee and Benjamin Topaz's engagement party! As you know, all of you are dear friends or family members of this joyful couple and they would like you to join them in this moment of happiness.", "Camila Weatherbee's reasoning makes sense. Toni has always been in love with Anna and yet Anna was in love with Benjamin. He could have murderered Benjamin so that he could have Anna.", "Was Camila right? She's lying dead on the couch. It would make sense for him to kill her after she accused him in front of everyone..."]
 //Everyone ADDITIONS
// "Benjamin Topaz is dead in the living room!"(this one is right after engagement party announcement), "Fred Borden has been murdered in the bathroom!"(this one is right after Ben), "Merida Evernever has been murdered in the kitchen!" (this one is right after Fred), "Camila Weatherbee is dead on the couch!" (this one is right after 'Camila's reasoning makes sense...'),"The game is over! Thanks to Katniss, Helen was revealed as the murderer before she could kill anyone else!" (last one, duh)
